development:
 adapter: mysql2
 encoding: utf8
 database: photo
 pool: 5
 username: root
 password: root

test:
 adapter: mysql2
 encoding: utf8
 database: photo
 pool: 5
 username: root
 password: root